name: AeroPwarp
version: 2.0.0
main: SchdowNVIDIA\PlayerWarps\Main
api: 4.0.0
author: Pydow, SchdowNVIDIA, FiePaw
description: PlayerWarps Plugin
depend:
  - EconomyAPI
commands:
  pwarp:
    description: "PlayerWarps command"
    permission: use.pwarp
permissions:
  use.pwarp:
    default: true
  pwarp.*:
    default: op
  pwarp.warps.2:
    default: true
  pwarp.warps.unlimited:
    default: true
