name: PlayerWarps
version: 1.0.0-BETA
main: SchdowNVIDIA\PlayerWarps\Main
api: 3.0.0
author: Pydow, SchdowNVIDIA
description: PlayerWarps Plugin
depend:
  - EconomyAPI
commands:
  pwarp:
    description: "PlayerWarps command"
    permission:
permissions:
  pwarp.*:
    default: op
    children:
      pwarp.warps.2:
        default: true
      pwarp.warps.unlimited:
        default: true